name: Udemy-API-Restfull

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Create SQL Server Container
      run: |
        docker run -d --name sqlserver_test \
          -e "ACCEPT_EULA=Y" \
          -e "MSSQL_SA_PASSWORD=Pass@word123" \
          -p 1433:1433 \
          mcr.microsoft.com/mssql/server:2022-latest
        
        echo "Aguardando o SQL Server iniciar..."
        timeout 90s bash -c "until docker exec sqlserver_test /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'Pass@word123' -Q 'SELECT 1' -C; do sleep 5; done"

    - name: Create SQL Server Database
      run: docker exec sqlserver_test /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'Pass@word123' -Q "IF DB_ID('api_restful_database') IS NULL CREATE DATABASE [api_restful_database]" -C

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore ./API-Restful/API-Restful.sln

    - name: Build ASP.NET 8 App
      run: dotnet build ./API-Restful/API-Restful.sln --configuration Release --no-restore
      
    - name: Test ASP.NET 8 App
      run: dotnet test ./API-Restful/API-Restful.sln --configuration Release --no-build --logger "console;verbosity=detailed"

    - name: Docker Compose Build
      run: docker compose build
      working-directory: ./API-Restful
